steemit/steem-js

README.md, lib/steem.js
I really like your work but wanted it to follow the standard node.js callback(err, results) pattern.  I updated your functions to callback with that pattern.  Updated the readme as well.
=> Update to follow standard node.js callback pattern

.gitignore, lib/api.js
I don't know what this function is supposed to do; definitely this is more
correct than what's there.
This closes #22.
=> Potential fix for setSubscribeCallback

lib/api.js, lib/methods.json
To support `getDiscussionsByBlog` and `getDiscussionsByComments`
=> Add support for comments and blog discussions

config.json
=> Update default websocket to wss://steemd.steemit.com

package.json
=> Remove crypto from package.json

README.md, doc/README.md, index.js, src/api/index.js, src/auth/ecc/index.js, src/auth/ecc/src/address.js, src/auth/ecc/src/key_public.js, src/auth/index.js, src/auth/serializer/src/types.js, src/config.js
=> Add set config fn

src/broadcast/index.js, src/formatter.js, test/broadcast.test.js
- Allow both string and object for json_metadata
- Add comment test
- Lowercase comment permlink on formatter helper
=> Allow string for json_metadata param

package.json, src/auth/ecc/src/aes.js, src/auth/ecc/src/hash.js, src/auth/index.js
This change should fix an issue reported by @feruzm.
=> Use 'create-hash' and 'create-hmac' instead of 'crypto'

package.json, test/comment.test.js
Comment options test was using 'steem' tags in json_metadata, i changed it to 'test' to get hidden on steemit.com.
=> Improve comment with options test

.npmignore
=> Fix preset requirement

package.json, scripts/index.rn.js, scripts/post-install.js
=> React-native poly fills

src/api/methods.json
Need this to add a SP delegation screen to aaroncox/vessel 👍
=> Added get_vesting_delegations method

doc/README.md, src/broadcast/operations.json
The operation `recover_account` was missing, i need it for steemconnect.
=> Add recover account operation

src/api/index.js
I've added a debug message on request that take too long to respond. The expected time to respond is ajustable with the config var `EXPECTED_RESPONSE_MS`. By default its 2 seconds.
=> Add debug message when steemd respond beyond an expected delay in ms

.editorconfig, src/api/index.js
make it more simple to read the code by calling onMessage function from ws.message handler rather than using events/emitter
=> ws client refactoring

package.json, scripts/index.rn.js, scripts/post-install.js
=> Update Reactnative script

README.md, examples/webpack-example/.gitignore, examples/webpack-example/README.md, examples/webpack-example/index.html, examples/webpack-example/package-lock.json, examples/webpack-example/package.json, examples/webpack-example/src/index.js, examples/webpack-example/webpack.config.js
This closes #200, related to #196
=> Add webpack usage example #200

examples/test-vote.js, src/broadcast/index.js
This closes #98. There'll be work on merging with the HTTP transport
branch.
=> Implement #98 pass back broadcasts' responses

package.json, src/api/transports/http.js
Change `isomorphic-fetch` to `fetch-ponyfill` to do http request for solve the issue #229 on ReactNative.
Close #229
=> Change isomorphic-fetch to fetch-ponyfill

.github/ISSUE_TEMPLATE.md
For some errors knowing exact operating system, node and npm version is crucial. Thus, we should ask for this information in issue template.
=> Add environment information to issue template

src/api/index.js, src/api/transports/http.js
Needed for condenser now that we will start calling other services through steem-js
=> Add method to do misc JSONRPC calls

package.json
This includes a couple of changes, most importantly the Appbase support.
=> release 0.6.5

README.md
This PR is for the minor documentation updates. 
Added badges for License and Steemit.chat. 
Updated Steemit.chat link to include the channel name so that it is easy for the users to join the channel directly instead of searching for it.
=> Updated README.md to include badges and Steemit.chat link

package.json
Please check action on the last few PRs so you know what all is changing before you hit the Big Green Button.
=> Bump to 0.6.6 for release

package.json
Changes since 0.6.7
* Respect appbase setting in http transport (previously only used for websockets)
=> Version 0.6.8

package.json
Changes since 0.6.8
- Update to "ws@3.3.2" to fix NSP issue #294
=> Version 0.6.9

src/api/transports/http.js
Add JSON specific headers `application/json` for JSON-RPC requests. Fix #297
=> Add JSON specific headers

src/config.js
=> Expose Config class for instantiation #302

package.json, src/api/index.js
=> add promise wrappers for call and signedCall

package.json, yarn.lock
This fixes compatibility problems with Vue CLI described in #398.
=> fix: update secure-random. fixes #398

README.md, package.json, src/api/index.js, src/auth/serializer/src/types.js, test/smt.test.js
Fix `useTestNet` option for SMT op serialization.
=> Updates to SMT op serialization

src/auth/serializer/src/types.js
=> Remove NAI checksum assertions

src/formatter.js, test/reputation.test.js
steem.formatter.reputation(0) should give 25.
also add tests.
=> Add Tests + Fix Rep 25 Error
