lib/api.js
Fixes errors in `Steem.send` callbacks when `data` isn't
defined. Changes what happens when an error is thrown, since `data`
isn't always passed to API-level callbacks.
=> Lousy macro patch to #20

lib/api-from-methods.js, lib/methods.json
Doesn't mess with the exported API. Adds a `lib/api-from-methods` module
exporting all API methods that use the
`this.send(apiName, options, callback)` scheme.
The generated functions work as follows. For every method in
`methods.json`, two functions are generated:
- `camelCaseMethodWith`
- `camelCaseMethod`
The usages are:
```javascript
api.camelCaseMethodWith(options, callback);
```
And:
```javascript
api.camelCaseMethod(param1, param2, callback);
```
`options` currently holds parameters with their names generated from the
source `lib/api.js` variable names. For example:
```javascript
api.getBlockWith({
blockNum: 1, // <- because `lib/api.js` called the variable `blockNum`
}, function (err, operation) {
console.log(err, operation);
});
api.getBlock(1, function (err, operation) { …
```
=> Initial implementation of API method codegen

src/broadcast/operations.json
Namely:
- `cancel_transfer_from_savings`
- `escrow_aprove`
- `fill_transfer_from_savings`
- `pow2`
- `transfer_from_savings`
- `transfer_to_savings`
The full list of all (new) methods in `steem` and supported here would
be:
This closes #45.
=> Adds a couple of missing broadcast methods

src/api/methods.json
get_key_references was moved to the own api "account_by_key_api".
=> get_key_references was moved to account_by_key_api

src/api/index.js
Example Issue:
1) submit 25 concurrent requests (inFlight = 25)
2) 10 messages get processed (inFlight = 15)
3) waitForSlot expects `inFlight < 10` to process more msgs
This change is to count only active (not queued) requests
=> inFlight should only count active requests

package.json, src/broadcast/index.js
`properties.timestamp` is undefined, causing clients to fall back to `Date.now()`, which seems to be a bit unreliable as we've had a handful of error reports the last 2 days.
This change fixes chain time access and removes the local time fallback. I notice that in the old steemjs code, this fallback didn't exist. So I think it should be fine to always rely on dynamic_global_props.
old strategy
https://github.com/steemit/condenser/blob/b662db62ecb2fa57fd7d6ae8e130fb009e24cfb0/shared/chain/transactions.js#L30-L31
new strategy
https://github.com/steemit/steem-js/blob/33e97ffc8af12247ee1780c5c2b18ac3d4ed1b85/src/broadcast/index.js#L59-L62
=> fix chain time access, remove local time fallback

package.json, src/auth/serializer/src/operations.js, test/Crypto.js, test/KeyFormats.js, test/all_types.js, test/api.test.js, test/broadcast.test.js, test/comment.test.js, test/memo.test.js, test/number_utils.js, test/operations_test.js, test/types_test.js
On this PR:
- Fix issue #124 by adding `comment_payout_beneficiaries` serializer.
- Add a test for broadcast comment + comment_options with beneficiaries.
- Separate test in sub-library (steem.auth, steem.broadcast, steem.api)
- npm test now run only steem.auth related functions by default (removed broadcast operations from default test).
=> Fix #124 and improve test

src/broadcast/index.js
I've had cases (batch scripts) where 15s was a bit too short. For convenience it might be good to increase default expiration to 60s. Are there any downsides to doing this?
=> change tx expiration from 15s to 60s

src/auth/serializer/src/operations.js
The operation `recover_account` seem to use an old serializer. I've changed the parameters to follow blockchain API: https://github.com/steemit/steem/blob/a670e4622d99248ecf1a2950acc167e8583bc15e/libraries/wallet/include/steemit/wallet/wallet.hpp#L912
=> Update `recover_account` serializer params

doc/README.md, package.json, src/auth/serializer/src/operations.js, src/broadcast/operations.json
Revert the changes on the operation `recover_account` serializer. I've successfully broadcast `recover_account` operation using `new_owner_authority` and `recent_owner_authority` parameters instead of `new_authority` and `recent_authority` like steem's header file suggest a here: https://github.com/steemit/steem/blob/6fd29bcb0f2c60b71d60a3be0686ffd3673e4658/libraries/wallet/wallet.cpp#L1360
=> Revert changes on `recover_account` serializer

src/broadcast/index.js
Changed the reference block used for broadcast transaction to use `header_block_num - 3`. Related issue here: https://github.com/steemit/steem-js/issues/144
Test working fine.
=> Use current block - 3 reference for broadcast tx

index.js, package.json, src/broadcast/index.js, src/browser.js, src/formatter.js, test/broadcast.test.js
Need to be tested for accounts with `savings_withdraws` and `open_orders`
Usage 
```js
import steem from 'steem';
steem.api.getAccountsAsync(["ned"]).then(user => {
return steem.formatter
.estimateAccountValue(user[0], { savings_withdraws: [], open_orders: [] })
.then(result => {
console.log("result", result);
});
});
```
=> Add Estimate account value formatter

index.js
This was breaking my browserify builds, I guess it would break on old node versions as well.
=> Don't use const outside of babelified source

test/broadcast.test.js
Changed test vote to avoid duplicate transaction. There was this issue firing https://github.com/steemit/steem/blob/3b138792c7f000bb702bd89b612d697bffd5de2f/libraries/chain/database.cpp#L2820 on CircleCi.
=> Fix test, avoid duplicate tx vote 

doc/README.md, examples/multisig.js
Add example using multi-signature for broadcast a vote.
=> Multisig example

examples/webpack-example/README.md, examples/webpack-example/webpack.config.js, package.json, src/api/methods.js, src/broadcast/index.js, src/broadcast/operations.js
So users don't need `json-loader` and `.json` as a detected module extension.
=> Remove usage of JSON files in steem-js

config.json, doc/README.md, package.json, src/api/index.js, test/api.test.js
This allows for setting the transport with a new configuration option `url`. It will leave the original methods of initiating steem-js intact to not break functionality for current users. Also, this adds the post-install build script npm module which makes it possible to load steem-js directly from a git url instead of from npm.
=> Set transport with url

src/api/transports/http.js
It's not possible for the moment to specify the api name using the new syntax and make it impossible to broadcast a tx see related issue: https://github.com/steemit/steem/issues/1282. I revert changes on the syntax to enable back broadcast API with JSON-RPC.
=> Use old api syntax for JSON-RPC

examples/add-key-auth.js, package.json, src/auth/serializer/src/types.js, src/broadcast/helpers.js, test/types_test.js
I have some trouble making this working and interested to have your feedback.
I created 2 helpers functions: `addKeyAuth` and `removeKeyAuth` for adding and removing a key inside user account `key_auths` array. It's using the operation `account_update` to do this change (https://github.com/steemit/steem-js/blob/d81a9a3a0f22cabc9a81fd8843801fdf980ecf08/src/broadcast/helpers.js#L109-L118) .
We have already the helpers functions `addAccountAuth` and `removeAccountAuth` that working well, but for some reason when i try to add a key instead of an account i got the error "Missing Active Authority". I've verified the private active WIF and account_update operation payload and they are valid.
Any idea what is wrong?
=> Add & remove a key in key_auth

src/api/index.js
Add support for an injectable external logger to *api*. Logger could be a function, or an object with functions for different log levels [à la quirky's logger](https://www.npmjs.com/package/logger).
Implementing logging within a function is as easy as this.log('level', [logitem1, ....[logitemN]])
Logging can be stopped by calling .setOptions({logging:false})
=> Added .logger support to .api.setOptions

src/broadcast/operations.js
The this mapping is used in SC2 Hot signing to detect the type of key to use for sign operation. The operations `account_witness_vote` and `account_witness_proxy` was key type set to `posting` while it require at least an `active` authority. This PR fix that and add other missing key type in `roles` array.
=> Fix mapping role for `account_witness_vote` and `account_witness_proxy` operations

doc/README.md, src/api/methods.js
Steem REST API (api.steemjs.com) rely on steem-js file `src/api/methods.js` to parse parameters. The request `https://api.steemjs.com/get_content_replies?author=siol&permlink=test` was failing because params were wrong in steem-js mapping
=> Fix params get_content_replies

package.json, webpack/makeConfig.js
When steem-js is located inside of node_modules of another project `exclude: /node_modules/` was  excluding all .js files not only local node_modules content, so it was failing to build.
I've checked it works without this exclude directive but I tested it only with node 8.5, probably more testing is needed.
I've also updated "build-browser" to always call local webpack to make sure the right version is called and there would no requirement for globally installed webpack.
=> fix condenser build with node 8.5 and webpack 1.5

config.json, src/api/index.js, src/api/methods.js, src/api/transports/base.js, src/api/transports/ws.js, test/api.test.js, test/broadcast.test.js, test/operations_test.js
This PR adds an option to the client, `useAppbaseApi`, which tells the Websocket transport to switch to the new `condenser_api` supplied with Appbase-enabled versions of steemd.
Incidental to this work was removing the Websocket transport's reliance on an obsolete pattern for calling APIs in steemd.
=> websocket client can now switch to appBase

package.json, yarn.lock
NSP is triggering a vulnerability on current `ws` package. On this PR i'm updating `ws` package to newest version 3.3.2 where the issue is resolved. See more detail about the vulnerability found here: https://nodesecurity.io/advisories/550
=> Update to "ws@3.3.2" to fix NSP issue

test/api.test.js
I've removed the dev instance from the test and use jussi prod instead since the availability is not certain and test were failing. The test are passing now for me:
=> Use jussi prod instead of dev instance to run useApiOptions test

src/auth/ecc/src/key_public.js, test/KeyFormats.js
Replaces #390 by @netuoso:
> Fixes https://github.com/steemit/steem-js/issues/267
> 
> Returns a null PublicKey for setting witness disabled.
> 
> Tested: https://steemd.com/tx/7883ed11b554247abdb93ff8d348e83e9ae1c022
=> Netuoso 267 fix invalid sequence disable witness

src/formatter.js
This causes an exception when trying to get `estimateAccountValue` for a user that is not yet cached.
Proposed fix for #423
=> Fix wrong usage of string template (fixes #423)

.circleci/config.yml
1.0 was deprecated, this adds a config file for 2.0
It passes tests and builds successfully on circle with this.
=> Add Circle CI 2.0 support

src/broadcast/index.js
While preparing a transaction for broadcast, steem-js obtains the previous block id by using `get_block`. Instead, it should use `get_block_header` which is more efficient for both the client and the server in terms of data transfer.
Closes #436
=> Switch to get_block_header for obtaining previous block id

package.json, src/auth/serializer/src/operations.js, test/hf20-accounts.test.js, test/hf21-sps.test.js
From @drov0 #447:
> Set the memo parameter in the account_update2 operation as optional as discussed in  #446
> Fixes #446
=> Community - Set the memo parameter in the account_update2 operation as optional

src/broadcast/index.js
should be an typo in the previous version:
- `useCommentPermlink` should be true when both `parent_author` and `parent_permlink` are needed.
=> Fix the condition error of useCommentPermlink

README.md, src/api/index.js, src/api/methods.js, test/api.test.js
Added rc_api.find_rc_accounts. For example:
```js
async function test() {
return await steem.api.findRcAccountsAsync(["justinsunsteemit"]);
}
```
Passing all tests `npm test`.
=> Add support of rc_api.find_rc_accounts

src/api/methods.js, test/api.test.js
This PR adds `get_expiring_vesting_delegations` to `steem.api` 
```js
steem.api.send(
"condenser_api",
{
method: "get_expiring_vesting_delegations",
params: [ 'justyy', '2024-08-12T20:28:30', 100 ]
},
function (err, res) {
console.log(err, res);
}
);
```
=> Add steem.api.getExpiringVestingDelegationsAsync

doc/README.md, src/api/methods.js, test/api.test.js
Get the change requests of recovery account for multiple accounts.
```js
steem.api.findChangeRecoveryAccountRequests(['justyy222', 'ety001', 'justyy'], function(err, data) {
console.log(err, data);
});
```
Return Example:
```js
{"requests":
[
{
"id":2238,
"account_to_recover":"justyy222",
"recovery_account":"happyukgo",
"effective_on":"2024-09-24T06:15:33"
}
]
}
```
=> Add steem.api.findChangeRecoveryAccountRequests

src/formatter.js, test/comment.test.js
Only return lowercase alphanumeric letters and dashes.
Fixes #330.
=> Fix formatter.commentPermLink
